### ISSUE TITLE
주문 알림 메세지 Slack Bot으로 변경

### ISSUE THREAD

**Issue by kbtapjm** [cnpst/zcp-admin-order#1]

**Comment by kbtapjm** [comment]
- 주문 알림 메세지는 어떤 채널에 전송할 것인가? 아니면 슬랙 봇이 설치 된 모든 채널에 메세지를 보낼것인가?

**Comment by kilsoo75** [comment]
@kbtapjm SK C&C Digital Service > **zseries-order** 채널에만 알람을 보내면 됩니다.
슬랙 봇이 설치 된 모든 채널에 보내면 난리 납니다~~

**Comment by kbtapjm** [comment]
@kilsoo75 테스트용으로 앱을 만들었는데 SRE에 적용 할 토큰 알려주시면 반영하겠습니다. 
Slack Bot : https://api.slack.com/apps/A010RRPR7R9
